### ISSUE TITLE
Maybe a typo in file "initial_dictionaries.py"

### ISSUE THREAD

**Issue by leisyracuse** [DrDaveShaw/INCHEM-Py#11]
Hi DrDaveShaw,

I just found a typo in line 162 and 163 of initial_dictionaries.py. I thought the "loss_array_temp" in these lines should be "gain_array_temp". Could you please take a look?

Best,
Lei

**Comment by DrDaveShaw** [comment]
Hi Lei, 

Thanks for bringing this up. I've had a look and I think it's correct as it is.

The reason the "loss_array_temp" is being added to the "temp_gain" list is that these are not the species that are being gained but are the species that the rate of species gain depends on. For example:

The reactions
A + B = C + D (rate constant k1)
C = D + F (rate constant k2)
D = A + G (rate constant k3)

Would give species D a rate equation of the form
dD/dt = ABk1 + Ck2 - Dk3

As gain or loss rate only depends on concentrations of species on the LHS of the reaction.

Hope that clarifies things.

Dave

**Comment by leisyracuse** [comment]
Hi Dave,

Thank you for clarification. It is very helpful to understand the program.

Best,
Lei
