### ISSUE TITLE
AER in initial_concentrations.txt

### ISSUE THREAD

**Issue by rs028** [DrDaveShaw/INCHEM-Py#15]
In the new version, the file `initial_concentrations.txt` contains the line:

`AER=0.0001388888888888889 ;`

should it be instead: `ACRate=0.0001388888888888889 ;`?

**Comment by DrDaveShaw** [comment]
Well spotted, It shouldn't make a difference at the moment, unless someone has a custom input called AER. I'll remove it from the initial conditions file as it's not needed.
