### ISSUE TITLE
INCHEM_extractor header

### ISSUE THREAD

**Issue by rs028** [DrDaveShaw/INCHEM-Py#16]
I noticed that `INCHEM_extractor.py` doesn't output a complete header, with the first column having no name.
To solve this, a `index_label` can be added to the write csv function, like this:
```
    out_data[i].to_csv("%s/%s/%s.csv" % (path,output_folder,i), 
                       columns = species_to_extract, index_label='Time')
```

**Comment by DrDaveShaw** [comment]
Thanks Roberto :)
