### ISSUE TITLE
Please use lower-case module names only

### ISSUE THREAD

**Issue by khinsen** [DrDaveShaw/INCHEM-Py#2]
The [Python style guide](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) says:

"Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged."

There is a good reason for this: operating systems don't agree on how to deal with case in filenames. Since Python module names map directly to filenames, this means that packages using mixed-case filenames may fail on some OS, or be damaged by copying the code between different OS.

**Comment by DrDaveShaw** [comment]
@khinsen Thank you for raising this issue and providing the explanation. 

It appears to apply to five of the modules which I will fix and also update the documentation. I will reply here when complete.
