### ISSUE TITLE
Avoid side effects in modules

### ISSUE THREAD

**Issue by khinsen** [DrDaveShaw/INCHEM-Py#3]
The script `settings.py` ends with
```python
if __name__ == "__main__":
    import modules.INCHEM_main
```
meaning that the simulation is run as a side effect of importing the module `modules.INCHEM.main`. This is generally considered bad practice; see [here](https://chrismorgan.info/blog/say-no-to-import-side-effects-in-python/) for a good explanation.

Relatedly, importing `settings.py` in `modules.INCHEM.main` and vice versa (i.e. a circular import) is considered bad style and makes it very hard to use either module safely for other purposes.

Recommendation: define a function `run_simulation(filename, particles, ...)` in `modules.INCHEM.main` and call it from `settings.py`. That avoids both forms of bad practices, and removes the need to manipulate `sys.path` in `modules.INCHEM.main`.

Alternatively, use `settings.py` for nothing else than defining parameters, and have another script `run_simulation.py` that imports both `settings` and `main`.

**Comment by DrDaveShaw** [comment]
Thank you for raising the issue with the linked explanation @khinsen  

I have created `run_inchem` as a function within `modules.INCHEM_main` which is called in `settings.py` as suggested (I will get around to issue #2 shortly).

I've left `settings.py` as the module to run to simulation.  I believe that users with limited coding experience will find it easier to run the same file that they change the majority of parameters in.  I'll commit the changes to close the issue.
