### ISSUE TITLE
Use idiomatic Python for processing sequences (lists, arrays)

### ISSUE THREAD

**Issue by khinsen** [DrDaveShaw/INCHEM-Py#5]
Many parts of the code look like translated Fortran code, making it both inefficient and hard to read.

Example from `modules.INCHEM_main` (comments removed):
```python
def ppool_density_calc(density_dict,ppool):
    ppool_new=np.zeros([len(ppool)]).tolist()
    for i in range(len(ppool)):
        ppool_new[i]=eval(ppool[i],{},density_dict)
    
    RO2=sum(ppool_new)
    return RO2
```
The list `ppool_new` is created in an inefficient way from an array, and moreover it is not needed at all because only the sum of its items ever matters. A more Pythonic version is
```python
def ppool_density_calc(density_dict,ppool):
    RO2 = 0.
    for p in ppool:
        RO2 += eval(p, {}, density_dict)
    return RO2
```
and some Python programmers would even prefer shortening this to:
```python
def ppool_density_calc(density_dict,ppool):
    return sum(eval(p, {}, density_dict) for p in ppool)
```

**Comment by DrDaveShaw** [comment]
I've been through and I think that this issue has been addressed with particular attention paid to where the code was translated Fortran. Closing the issue.
