### ISSUE TITLE
Is the use of `global` really necessary?

### ISSUE THREAD

**Issue by khinsen** [DrDaveShaw/INCHEM-Py#6]
Two functions in `modules.INCHEM_main` modify a global variable `particle_dict` via
```python
    global particle_dict
    if particles == 1:
        particle_dict = particle_calcs(part_calc_dict,density_dict)
    else:
        particle_dict={}
```
The use of `global` in Python is generally discouraged, because it makes the code hard to understand and often introduces hard to find bugs. In this case, the necessity to use `global` is not obvious. Passing around `particle_dict` from function to function, just like all other values, looks very feasible.

**Comment by DrDaveShaw** [comment]
The use of `global` has been removed from the functions within `modules.INCHEM_main` and the functions continue to work as expected. `global` usage was added some time ago to solve an issue that is no longer present.

As such I'll close the issue.
